name: mawaqit_quran_listening
description: "A Flutter package that provides Quran listening functionality, enabling easy access, display, and navigation of Surahs and Ayahs with audio playback capabilities."
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  provider: ^6.1.1
  path_provider: ^2.0.9
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.1


  # Audio player
  just_audio: ^0.10.4
  just_audio_background: ^0.0.1-beta.17

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1

  # UI
  sizer: ^2.0.15
  flutter_svg: ^2.0.3
  fluttertoast: ^8.0.9
  modal_bottom_sheet: ^3.0.0-pre
  skeletonizer:

  # Utilities
  super_converter: ^1.1.0
  collection: ^1.18.0

  # Internationalization
  mawaqit_mobile_i18n:
    git:
      url: https://github.com/mawaqit/mawaqit-mobile-i18n.git
      ref: main

#  # Main app dependencies for icons
#  mawaqit:
#    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icons/
    - assets/reciters/
    - assets/fonts/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MawaqitIcons
      fonts:
        - asset: assets/fonts/MawaqitIcons.ttf
    - family: watch
      fonts:
        - asset: assets/fonts/watch_icons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
